name: Test

on:
  push:

jobs:
  test:
    container: ghcr.io/kubeitron/gitops-container:main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Test
        run: |
          echo "Test"
          ansible-playbook --version
          ls -lash
          pwd

